name: linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ "**" ]

jobs:
  perl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install libs from apt
        run: sudo apt-get update && sudo apt-get install libdatetime-perl bioperl
      
      - name: Test perl installation
        run: perl -V
      
      - name: Install cpanm
        run: sudo cpan App::cpanminus
      
      - name: Install itap dependencies
        run: sudo cpanm --installdeps .
      
      - name: Run itap tests
        run: |
           ./itap -help
           ./itap
           ./itap -t -f -r