name: linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ "**" ]

jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.8'
          - '5.10'
          - '5.16'
          - 'latest'
          - 'threaded'

    container:
      image: perl:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v2
      - name: Apt plugins
        run: sudo apt-get update && apt-get install libdatetime-perl bioperl
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: cpanm --installdeps .
      - name: Run Tests
        run: ./itap -help