name: macos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ "**" ]

jobs:
  perl:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install perl
        run: brew install perl
      
      - name: Test installation
        run: perl -V
      
      - name: Install cpanm
        run: brew install cpanminus
      
      - name: Install dependencies
        run: sudo cpanm --installdeps .
      
      - name: Run tests
        run: ./itap -help