name: macos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ "**" ]

jobs:
  perl:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install libs from apt
        run: sudo apt-get update && sudo apt-get install libdatetime-perl bioperl

      - name: Install perl
        run: brew install perl
      
      - name: Test perl installation
        run: perl -V
      
      - name: Install cpanm
        run: brew install cpanminus
      
      - name: Install itap dependencies
        run: sudo cpanm --installdeps .
      
      - name: Run itap tests
        run: |
           ./itap -help
