name: windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ "**" ]

jobs:
  perl:
    runs-on: windows-latest
    steps:
      - name: Set up Perl
      - uses: actions/checkout@v2
        run: |
          choco install strawberryperl
          echo "C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin" >> $GITHUB_PATH
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: cpanm --installdeps .
      - name: Run Tests
        run: ./perl -help