name: windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ "**" ]

jobs:
  perl:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install perl
        run: |
          choco install strawberryperl
          echo "C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin" >> $GITHUB_PATH
      
      - name: Test perl installation
        run: perl -V

      - name: Install itap dependencies
        run: cpanm --sudo --force --installdeps .

      - name: Run itap tests
        run: ./perl -help